=== Procurement-PoE/Procurement/POEApi.Model/Settings.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Settings" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Settings">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Ratios" minOccurs="1" maxOccurs="1" />
        <xs:element ref="PopularGems" minOccurs="1" maxOccurs="1" />
        <xs:element ref="PopularGems_RU" minOccurs="1" maxOccurs="1" />
        <xs:element ref="UserSettings" minOccurs="1" maxOccurs="1" />
        <xs:element ref="ProxySettings" minOccurs="1" maxOccurs="1" />
        <xs:element ref="ShopSettings" minOccurs="1" maxOccurs="1" />
        <xs:element ref="Lists" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--Level 1-->
  <xs:element name="Ratios">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Orb" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="ChaosAmount" type="xs:decimal" use="required" />
            <xs:attribute name="OrbAmount" type="xs:decimal" use="required" />
            <xs:attribute name="type" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="UserSettings">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Setting">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="AccountLogin" type="AccountLogin" minOccurs="1" maxOccurs="1" />
              <xs:element name="AccountPassword" type="AccountPassword" minOccurs="1" maxOccurs="1" />
              <xs:element name="AccountName" type="AccountName" minOccurs="1" maxOccurs="1" />
              <xs:element name="UseSessionID" type="UseSessionID" minOccurs="1" maxOccurs="1" />
              <xs:element name="FavoriteLeague" type="FavoriteLeague" minOccurs="1" maxOccurs="1" />
              <xs:element name="FavoriteCharacter" type="FavoriteCharacter" minOccurs="1" maxOccurs="1" />
              <xs:element name="CompactMode" type="CompactMode" minOccurs="1" maxOccurs="1" />
              <xs:element name="DownloadOnlyMyLeagues" type="DownloadOnlyMyLeagues" minOccurs="1" maxOccurs="1" />
              <xs:element name="DownloadOnlyMyCharacters" type="DownloadOnlyMyCharacters" minOccurs="1" maxOccurs="1" />
              <xs:element name="CurrencyDistributionMetric" type="CurrencyDistributionMetric" minOccurs="1" maxOccurs="1" />
              <xs:element name="EmbedBuyouts" type="EmbedBuyouts" minOccurs="1" maxOccurs="1" />
              <xs:element name="BuyoutItemsOnlyVisibleInBuyoutsTag" type="BuyoutItemsOnlyVisibleInBuyoutsTag" minOccurs="1" maxOccurs="1" />
              <xs:element name="CheckForUpdates" type="CheckForUpdates" minOccurs="1" maxOccurs="1" />
              <xs:element name="SeverType" type="ServerType" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ProxySettings">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Setting">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Enabled" type="Enabled" minOccurs="1" maxOccurs="1" />
              <xs:element name="Username" type="Username" minOccurs="1" maxOccurs="1" />
              <xs:element name="Password" type="Password" minOccurs="1" maxOccurs="1" />
              <xs:element name="Domain" type="Domain" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ShopSettings">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Shop">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="League" type="xs:string" minOccurs="1" maxOccurs="1" />
              <xs:element name="ThreadId" type="xs:string" minOccurs="1" maxOccurs="1" />
              <xs:element name="ThreadTitle" type="xs:string" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Lists">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="List" minOccurs="4" maxOccurs="4" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PopularGems">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Gem" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PopularGems_RU">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Gem" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--Level 2-->
  <xs:complexType name="AccountLogin">
    <xs:attribute name="name" fixed="AccountLogin" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="AccountPassword">
    <xs:attribute name="name" fixed="AccountPassword" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="AccountName">
    <xs:attribute name="name" fixed="AccountName" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="UseSessionID">
    <xs:attribute name="name" fixed="UseSessionID" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:boolean" use="required"/>
  </xs:complexType>
  <xs:complexType name="FavoriteLeague">
    <xs:attribute name="name" fixed="FavoriteLeague" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="FavoriteCharacter">
    <xs:attribute name="name" fixed="FavoriteCharacter" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="CompactMode">
    <xs:attribute name="name" fixed="CompactMode" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:boolean" use="required"/>
  </xs:complexType>
  <xs:complexType name="DownloadOnlyMyLeagues">
    <xs:attribute name="name" fixed="DownloadOnlyMyLeagues" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:boolean" use="required"/>
  </xs:complexType>
  <xs:complexType name="DownloadOnlyMyCharacters">
    <xs:attribute name="name" fixed="DownloadOnlyMyCharacters" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:boolean" use="required"/>
  </xs:complexType>
  <xs:complexType name="CurrencyDistributionMetric">
    <xs:attribute name="name" fixed="CurrencyDistributionMetric" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="EmbedBuyouts">
    <xs:attribute name="name" fixed="EmbedBuyouts" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:boolean" use="required"/>
  </xs:complexType>
  <xs:complexType name="BuyoutItemsOnlyVisibleInBuyoutsTag">
    <xs:attribute name="name" fixed="BuyoutItemsOnlyVisibleInBuyoutsTag" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:boolean" use="required"/>
  </xs:complexType>
  <xs:complexType name="CheckForUpdates">
    <xs:attribute name="name" fixed="CheckForUpdates" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:boolean" use="required"/>
  </xs:complexType>
  <xs:complexType name="Enabled">
    <xs:attribute name="name" fixed="Enabled" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:boolean" use="required"/>
  </xs:complexType>
  <xs:complexType name="Username">
    <xs:attribute name="name" fixed="Username" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="Password">
    <xs:attribute name="name" fixed="Password" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="Domain">
    <xs:attribute name="name" fixed="Domain" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="ServerType">
    <xs:attribute name="name" fixed="ServerType" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:element name="Item">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:string" />
      <xs:attribute name="value" use="required" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="List">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Item" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="value" use="required" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="MyLeagues" />
            <xs:enumeration value="MyTabs" />
            <xs:enumeration value="MyCharacters" />
            <xs:enumeration value="AdditionalTemplates" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Procurement-PoE/Procurement/POEApi.Model/Settings.xml
<?xml version="1.0" encoding="utf-8" ?>
<Settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Settings.xsd">
  <Ratios>
    <Orb type="Mirror" OrbAmount="1" ChaosAmount="450" />
    <Orb type="Eternal" OrbAmount="1" ChaosAmount="50" />
    <Orb type="Imprint" OrbAmount="1" ChaosAmount="0" />
    <Orb type="Exalted" OrbAmount="1" ChaosAmount="20" />
    <Orb type="Divine" OrbAmount="1" ChaosAmount="8" />
    <Orb type="GemCutterPrism" OrbAmount="1" ChaosAmount="2" />
    <Orb type="Chisel" OrbAmount="2.5" ChaosAmount="1" />
    <Orb type="Regal" OrbAmount="1" ChaosAmount="2" />
    <Orb type="Chaos" OrbAmount="1" ChaosAmount="1" />
    <Orb type="Regret" OrbAmount="1" ChaosAmount="1" />
    <Orb type="Blessed" OrbAmount="2" ChaosAmount="1" />
    <Orb type="Scouring" OrbAmount="2.5" ChaosAmount="1" />
    <Orb type="Fusing" OrbAmount="2.5" ChaosAmount="1" />
    <Orb type="Alchemy" OrbAmount="2.5" ChaosAmount="1" />
    <Orb type="AlchemyShard" OrbAmount="40" ChaosAmount="1" />
    <Orb type="Chance" OrbAmount="8" ChaosAmount="1" />
    <Orb type="JewelersOrb" OrbAmount="10" ChaosAmount="1" />
    <Orb type="Alteration" OrbAmount="20" ChaosAmount="1" />
    <Orb type="Chromatic" OrbAmount="20" ChaosAmount="1" />
    <Orb type="VaalOrb" OrbAmount="1" ChaosAmount="1" />    "
  </Ratios>
  <PopularGems>
    <Gem name="Cast when Damage Taken" />
    <Gem name="Cast On Critical Strike" />
    <Gem name="Blood Magic" />
    <Gem name="Item Quantity" />
    <Gem name="Life Gain on Hit" />
    <Gem name="Life Leech" />
    <Gem name="Multistrike" />
    <Gem name="Reduced Mana" />
    <Gem name="Spell Totem" />
    <Gem name="Chain" />
    <Gem name="Faster Attacks" />
    <Gem name="Greater Multiple Projectiles" />
    <Gem name="Lesser Multiple Projectiles" />
    <Gem name="Added Chaos Damage" />
    <Gem name="Item Rarity" />
    <Gem name="Concentrated Effect" />
    <Gem name="Elemental Hit" />
    <Gem name="Elemental Proliferation" />
    <Gem name="Elemental Weakness" />
    <Gem name="Multistrike" />
    <Gem name="Temporal Chains" />
    <Gem name="Faster Casting" />
  </PopularGems>
  <UserSettings>
    <Setting name="AccountLogin" value="" />
    <Setting name="AccountPassword" value="" />
    <Setting name="AccountName" value="" />
    <Setting name="UseSessionID" value="false" />
    <Setting name="FavoriteLeague" value="" />
    <Setting name="FavoriteCharacter" value="" />
    <Setting name="CompactMode" value="false" />
    <Setting name="DownloadOnlyMyLeagues" value="false" />
    <Setting name="DownloadOnlyMyCharacters" value="false" />
    <Setting name="CurrencyDistributionMetric" value="Chaos" />
    <Setting name="EmbedBuyouts" value="True" />
    <Setting name="BuyoutItemsOnlyVisibleInBuyoutsTag" value="False" />
    <Setting name="OnlyDisplayBuyouts" value="false" />
    <Setting name="CheckForUpdates" value="True" />
    <Setting name="PoeTradeRefreshEnabled" value="false" />
    <Setting name="PoeTradeRefreshUrl" value="" />
  </UserSettings>
  <ProxySettings>
    <Setting name="Enabled" value="False" />
    <Setting name="Username" value="" />
    <Setting name="Password" value="" />
    <Setting name="Domain" value="" />
  </ProxySettings>
  <ShopSettings>
    <Shop League="Standard" ThreadId="" ThreadTitle="" />
    <Shop League="Hardcore" ThreadId="" ThreadTitle="" />
    <Shop League="Bloodlines" ThreadId="" ThreadTitle="" />
    <Shop League="Torment" ThreadId="" ThreadTitle="" />
  </ShopSettings>
  <Lists>
    <List name="MyLeagues">
      <Item value="Standard" />
      <Item value="Hardcore" />
      <Item value="Torment" />
      <Item value="Bloodlines" />
    </List>
    <List name="MyTabs">
      <!--If you only want Procurement to download specific tabs list them here, eg :-->
      <!--<Item value="Shop" />-->
    </List>
    <List name="MyCharacters">
      <!--If you only want Procurement to download specific characters list them here, eg :-->
      <!--<Item value="SomeCharacter" />-->
    </List>
    <List name="AdditionalTemplates">
      <!--Add yours own templates here. Eg-->
      <!--<Item value="LvlingShop.txt"/>-->
    </List>
    <List name="IgnoreTabsInRecipes" />
  </Lists>
</Settings>
